# Setup
title:            Seth Neller
tagline:          Home
description:      <p style="font-size:75%;"> Assistant Professor <br/> Department of Economics and <br/> Boyd Center for Bus. & Econ. Research <br/> University of Tennessee </br> </br> seth.neller@gmail.com </p>
url:              https://sethneller.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Seth Neller'
  url:            https://twitter.com/sethneller

github:
  repo:           https://github.com/sethneller/sethneller.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

