# Setup
title:            Seth Neller
tagline:          Home
description:      Assistant Professor <br/> Dept. of Economics and <br/> Boyd Center for Business & Economic Research <br/> University of Tennessee <hr> seth.neller@gmail.com
url:              https://sethneller.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Seth Neller'
  url:            https://twitter.com/sethneller

github:
  repo:           https://github.com/sethneller/sethneller.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

